feat: change tick/colorscale scales
swiss-seismological-service/REIA-web pull request #57
Opened 2024-07-18 15:55 UTC by romanoe

#54 

### Reproject Value Ranges:
* Change the value range from [0.1, 10M] to [1M, 10M].
* Adjust the value range from [0, 50] to [5, 50].

### Update Minimum Value Thresholds:
* Modify the thresholds for the minimum value to reflect changes both in the labels and the colorscale.

### Adjust Damage Graph Parameters:
* Update the xDomain, xTickValues, and the symlog constant specifically for the damage graph.

**Note**: For the damage graphs, the reprojection of values in the range [5, 50] is based on the condition that d.damage_pc90 >= 5. Feel free to change it if you prefer `d.damage_mean`

2024-07-22 07:40 UTC, romanoe commented
Edit: conditional filter for input data is not needed as the domain is constraint to [5, 500'000]

2024-07-22 10:31 UTC, schmidni commented
ok, this looks better, can you deploy it on ermd and I'll have a look again at the product?

2024-07-22 11:13 UTC, romanoe commented
> ok, this looks good, I guess you have visually tested it?
> 
> can you deploy it on ermd and I'll have a look again at the product?

Yes, I visually tested it and can deploy on ermd for the final checks. Would you prefer that I merge the changes into the main branch before deploying, or should I deploy the current branch (branch feat/tick-values) before merging  ?

2024-07-22 14:18 UTC, romanoe commented
Branch deployed on ermd 🚀

2024-07-23 08:05 UTC, schmidni commented on src/js/webcomponents/LossScale.js
> +            fatalities: value <= 1 ? Math.round(value) : '0',
I understand the idea, but it is not working correctly since you'd have to adjust the color scale too:
/reia.html?oid=70ad4c50-1cfd-4142-be01-32ddbfa42c30&canton=TI

Let's ask later in the meeting how we wanna handle it if the value is between 0.5 and 1.

2024-07-24 13:32 UTC, romanoe commented
My apologies, I forgot to ensure that loss_mean is also smaller than 1 before setting pc10 to 0... sorry 😭

2024-07-25 09:14 UTC, schmidni requested changes
As far as I can see, this should work.

You can implement the tiny change I requested, and then deploy this branch again to ermd.

2024-07-25 09:14 UTC, schmidni commented on src/js/webcomponents/LossScale.js
> +        const minValue = Math.round(this.thresholds[0]);
if, for some reason, somebody wanted to change the thresholds from 0.5, 5, 50.... to 0.2, 2, 20..... then this would fail. It's a small thing, but if you just use Math.ceil() instead of round, then this is fool-proof :)

2024-07-25 09:41 UTC, romanoe commented
https://github.com/swiss-seismological-service/REIA-web/pull/57/commits/357687bc6522acbcdb287d2ce3fcb9b5922e3654 & deployed on ermd

2024-07-25 11:29 UTC, schmidni approved these changes

2024-07-25 11:30 UTC, schmidni commented
great, in that case you can merge, deploy to erma, as well as making sure that those changes will also be on the scales on the sed website.

2024-07-25 16:14 UTC, merged

2024-07-25 16:20 UTC, romanoe commented
Deployed on erma